[env:ILI9341]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv       ; 4MB (sem flash externo 25Q32)

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12

; ============================================
; Se ILI9341 nao funcionar, teste o env ST7789:
; No VS Code: clique no seletor de ambiente
; ou rode: pio run -e ST7789
; ============================================

[env:ST7789]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv

build_flags =
    -DCYD_ST7789=1

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
